package kieranvs.avatar.block;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelStatueRoku extends ModelBase{

	ModelRenderer Stand1;
	ModelRenderer Stand2;
	ModelRenderer PonyTail;
	ModelRenderer LeftHeadspike;
	ModelRenderer RightHeadspike;
	ModelRenderer HairClip;
	ModelRenderer Beard1Left;
	ModelRenderer Beard1Right;
	ModelRenderer Beard2Left;
	ModelRenderer Beard2Right;
	ModelRenderer Beard3;
	ModelRenderer Beard4Left;
	ModelRenderer Beard4Right;
	ModelRenderer Beard5Left;
	ModelRenderer Beard5Right;
	ModelRenderer Beard6Left;
	ModelRenderer Beard6Right;
	ModelRenderer Beard7Left;
	ModelRenderer Beard7Right;
	ModelRenderer Hair;
	ModelRenderer FaceHairRight;
	ModelRenderer FaceHairLeft;
	ModelRenderer BackHair1;
	ModelRenderer BackHairTail;
	ModelRenderer LeftShoulder;
	ModelRenderer RightShoulder;
	ModelRenderer RightDress;
	ModelRenderer LeftDress;
	ModelRenderer Head;
	ModelRenderer Body;
	ModelRenderer RightArm;
	ModelRenderer LeftArm;
	ModelRenderer RightLeg;
	ModelRenderer LeftLeg;

	public ModelStatueRoku(){
		textureWidth = 128;
		textureHeight = 128;

		Stand1 = new ModelRenderer(this, 87, 0);
		Stand1.addBox(-6F, 0F, -4F, 12, 2, 8);
		Stand1.setRotationPoint(0F, 21F, 0F);
		Stand1.setTextureSize(128, 128);
		Stand1.mirror = true;
		setRotation(Stand1, 0F, 0F, 0F);
		Stand2 = new ModelRenderer(this, 79, 11);
		Stand2.addBox(-7F, 2F, -5F, 14, 1, 10);
		Stand2.setRotationPoint(0F, 21F, 0F);
		Stand2.setTextureSize(128, 128);
		Stand2.mirror = true;
		setRotation(Stand2, 0F, 0F, 0F);
		PonyTail = new ModelRenderer(this, 37, 85);
		PonyTail.addBox(-1F, -3F, -1F, 2, 2, 2);
		PonyTail.setRotationPoint(0F, -11F, 0F);
		PonyTail.setTextureSize(128, 128);
		PonyTail.mirror = true;
		setRotation(PonyTail, 0F, 0F, 0F);
		LeftHeadspike = new ModelRenderer(this, 46, 54);
		LeftHeadspike.addBox(1F, -6F, 0F, 0, 4, 1);
		LeftHeadspike.setRotationPoint(0.1F, -11F, 0F);
		LeftHeadspike.setTextureSize(128, 128);
		LeftHeadspike.mirror = true;
		setRotation(LeftHeadspike, 0F, 0F, 0F);
		RightHeadspike = new ModelRenderer(this, 46, 54);
		RightHeadspike.addBox(-1F, -6F, 0F, 0, 4, 1);
		RightHeadspike.setRotationPoint(-0.1F, -11F, 0F);
		RightHeadspike.setTextureSize(128, 128);
		RightHeadspike.mirror = true;
		setRotation(RightHeadspike, 0F, 0F, 0F);
		HairClip = new ModelRenderer(this, 46, 48);
		HairClip.addBox(-2F, -4.5F, 1F, 4, 1, 0);
		HairClip.setRotationPoint(0F, -11F, 0F);
		HairClip.setTextureSize(128, 128);
		HairClip.mirror = true;
		setRotation(HairClip, 0F, 0F, 0F);
		Beard1Left = new ModelRenderer(this, 26, 107);
		Beard1Left.addBox(0F, 0F, 0F, 1, 5, 1);
		Beard1Left.setRotationPoint(3F, -6F, -5F);
		Beard1Left.setTextureSize(128, 128);
		Beard1Left.mirror = true;
		setRotation(Beard1Left, 0F, 0F, 0F);
		Beard1Right = new ModelRenderer(this, 26, 107);
		Beard1Right.addBox(0F, 0F, 0F, 1, 5, 1);
		Beard1Right.setRotationPoint(-4F, -6F, -5F);
		Beard1Right.setTextureSize(128, 128);
		Beard1Right.mirror = true;
		setRotation(Beard1Right, 0F, 0F, 0F);
		Beard2Left = new ModelRenderer(this, 0, 107);
		Beard2Left.addBox(0F, 0F, 0F, 2, 7, 1);
		Beard2Left.setRotationPoint(1F, -5F, -5F);
		Beard2Left.setTextureSize(128, 128);
		Beard2Left.mirror = true;
		setRotation(Beard2Left, 0F, 0F, 0F);
		Beard2Right = new ModelRenderer(this, 0, 107);
		Beard2Right.addBox(0F, 0F, 0F, 2, 7, 1);
		Beard2Right.setRotationPoint(-3F, -5F, -5F);
		Beard2Right.setTextureSize(128, 128);
		Beard2Right.mirror = true;
		setRotation(Beard2Right, 0F, 0F, 0F);
		Beard3 = new ModelRenderer(this, 34, 106);
		Beard3.addBox(0F, 0F, 0F, 2, 10, 1);
		Beard3.setRotationPoint(-1F, -4F, -5F);
		Beard3.setTextureSize(128, 128);
		Beard3.mirror = true;
		setRotation(Beard3, 0F, 0F, 0F);
		Beard4Left = new ModelRenderer(this, 0, 95);
		Beard4Left.addBox(0F, 0F, 0F, 1, 8, 1);
		Beard4Left.setRotationPoint(4F, -9F, -4F);
		Beard4Left.setTextureSize(128, 128);
		Beard4Left.mirror = true;
		setRotation(Beard4Left, 0F, 0F, 0F);
		Beard4Right = new ModelRenderer(this, 0, 95);
		Beard4Right.addBox(0F, 0F, 0F, 1, 8, 1);
		Beard4Right.setRotationPoint(-5F, -9F, -4F);
		Beard4Right.setTextureSize(128, 128);
		Beard4Right.mirror = true;
		setRotation(Beard4Right, 0F, 0F, 0F);
		Beard5Left = new ModelRenderer(this, 10, 100);
		Beard5Left.addBox(0F, 0F, 0F, 1, 7, 2);
		Beard5Left.setRotationPoint(4F, -9F, -3F);
		Beard5Left.setTextureSize(128, 128);
		Beard5Left.mirror = true;
		setRotation(Beard5Left, 0F, 0F, 0F);
		Beard5Right = new ModelRenderer(this, 10, 100);
		Beard5Right.addBox(0F, 0F, 0F, 1, 7, 2);
		Beard5Right.setRotationPoint(-5F, -9F, -3F);
		Beard5Right.setTextureSize(128, 128);
		Beard5Right.mirror = true;
		setRotation(Beard5Right, 0F, 0F, 0F);
		Beard6Left = new ModelRenderer(this, 0, 82);
		Beard6Left.addBox(0F, 0F, 0F, 1, 6, 5);
		Beard6Left.setRotationPoint(4F, -9F, -1F);
		Beard6Left.setTextureSize(128, 128);
		Beard6Left.mirror = true;
		setRotation(Beard6Left, 0F, 0F, 0F);
		Beard6Right = new ModelRenderer(this, 0, 82);
		Beard6Right.addBox(0F, 0F, 0F, 1, 6, 5);
		Beard6Right.setRotationPoint(-5F, -9F, -1F);
		Beard6Right.setTextureSize(128, 128);
		Beard6Right.mirror = true;
		setRotation(Beard6Right, 0F, 0F, 0F);
		Beard7Left = new ModelRenderer(this, 20, 94);
		Beard7Left.addBox(0F, 0F, 0F, 1, 2, 8);
		Beard7Left.setRotationPoint(4F, -11F, -4F);
		Beard7Left.setTextureSize(128, 128);
		Beard7Left.mirror = true;
		setRotation(Beard7Left, 0F, 0F, 0F);
		Beard7Right = new ModelRenderer(this, 20, 94);
		Beard7Right.addBox(0F, 0F, 0F, 1, 2, 8);
		Beard7Right.setRotationPoint(-5F, -11F, -4F);
		Beard7Right.setTextureSize(128, 128);
		Beard7Right.mirror = true;
		setRotation(Beard7Right, 0F, 0F, 0F);
		Hair = new ModelRenderer(this, 0, 71);
		Hair.addBox(0F, 0F, 0F, 8, 1, 9);
		Hair.setRotationPoint(-4F, -12F, -5F);
		Hair.setTextureSize(128, 128);
		Hair.mirror = true;
		setRotation(Hair, 0F, 0F, 0F);
		FaceHairRight = new ModelRenderer(this, 0, 48);
		FaceHairRight.addBox(0F, 0F, 0F, 1, 1, 1);
		FaceHairRight.setRotationPoint(-4F, -11F, -5F);
		FaceHairRight.setTextureSize(128, 128);
		FaceHairRight.mirror = true;
		setRotation(FaceHairRight, 0F, 0F, 0F);
		FaceHairLeft = new ModelRenderer(this, 0, 48);
		FaceHairLeft.addBox(0F, 0F, 0F, 1, 1, 1);
		FaceHairLeft.setRotationPoint(3F, -11F, -5F);
		FaceHairLeft.setTextureSize(128, 128);
		FaceHairLeft.mirror = true;
		setRotation(FaceHairLeft, 0F, 0F, 0F);
		BackHair1 = new ModelRenderer(this, 0, 59);
		BackHair1.addBox(0F, 0F, 0F, 8, 9, 1);
		BackHair1.setRotationPoint(-4F, -11F, 4F);
		BackHair1.setTextureSize(128, 128);
		BackHair1.mirror = true;
		setRotation(BackHair1, 0F, 0F, 0F);
		BackHairTail = new ModelRenderer(this, 44, 113);
		BackHairTail.addBox(0F, 0F, 0F, 4, 10, 1);
		BackHairTail.setRotationPoint(-2F, -10F, 5F);
		BackHairTail.setTextureSize(128, 128);
		BackHairTail.mirror = true;
		setRotation(BackHairTail, 0F, 0F, 0F);
		LeftShoulder = new ModelRenderer(this, 0, 120);
		LeftShoulder.addBox(0F, 0F, 0F, 6, 2, 5);
		LeftShoulder.setRotationPoint(4F, -3F, -2F);
		LeftShoulder.setTextureSize(128, 128);
		LeftShoulder.mirror = true;
		setRotation(LeftShoulder, 0.2602503F, 0F, 0.3346075F);
		RightShoulder = new ModelRenderer(this, 0, 120);
		RightShoulder.addBox(-6F, 0F, 0F, 6, 2, 5);
		RightShoulder.setRotationPoint(-4F, -3F, -2F);
		RightShoulder.setTextureSize(128, 128);
		RightShoulder.mirror = true;
		setRotation(RightShoulder, 0.2230717F, 0F, -0.3346075F);
		RightDress = new ModelRenderer(this, 55, 0);
		RightDress.addBox(0F, 0F, 0F, 1, 12, 4);
		RightDress.setRotationPoint(-4F, 10F, -2.1F);
		RightDress.setTextureSize(128, 128);
		RightDress.mirror = true;
		setRotation(RightDress, 0F, 0F, 0.0743572F);
		LeftDress = new ModelRenderer(this, 55, 0);
		LeftDress.addBox(0F, 0F, 0F, 1, 12, 4);
		LeftDress.setRotationPoint(3F, 10F, -2.1F);
		LeftDress.setTextureSize(128, 128);
		LeftDress.mirror = true;
		setRotation(LeftDress, 0F, 0F, -0.0743572F);
		Head = new ModelRenderer(this, 0, 0);
		Head.addBox(-4F, -8F, -4F, 8, 8, 8);
		Head.setRotationPoint(0F, -3F, 0F);
		Head.setTextureSize(128, 128);
		Head.mirror = true;
		setRotation(Head, 0F, 0F, 0F);
		Body = new ModelRenderer(this, 16, 16);
		Body.addBox(-4F, 0F, -2F, 8, 12, 4);
		Body.setRotationPoint(0F, -3F, 0F);
		Body.setTextureSize(128, 128);
		Body.mirror = true;
		setRotation(Body, 0F, 0F, 0F);
		RightArm = new ModelRenderer(this, 40, 16);
		RightArm.addBox(-2F, -1F, -1F, 4, 12, 4);
		RightArm.setRotationPoint(-5F, -1F, 0F);
		RightArm.setTextureSize(128, 128);
		RightArm.mirror = true;
		setRotation(RightArm, 0.2602503F, 0F, -0.4461433F);
		LeftArm = new ModelRenderer(this, 40, 16);
		LeftArm.addBox(-2F, -1F, -1F, 4, 12, 4);
		LeftArm.setRotationPoint(5F, -1F, 0F);
		LeftArm.setTextureSize(128, 128);
		LeftArm.mirror = true;
		setRotation(LeftArm, 0.2602503F, 0F, 0.4461433F);
		RightLeg = new ModelRenderer(this, 0, 16);
		RightLeg.addBox(-2F, 0F, -2F, 4, 12, 4);
		RightLeg.setRotationPoint(-2F, 9F, 0F);
		RightLeg.setTextureSize(128, 128);
		RightLeg.mirror = true;
		setRotation(RightLeg, 0F, 0F, 0F);
		LeftLeg = new ModelRenderer(this, 0, 16);
		LeftLeg.addBox(-2F, 0F, -2F, 4, 12, 4);
		LeftLeg.setRotationPoint(2F, 9F, 0F);
		LeftLeg.setTextureSize(128, 128);
		LeftLeg.mirror = true;
		setRotation(LeftLeg, 0F, 0F, 0F);
	}
	
	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		render(f5);
	}

	public void render(float f5){
		Stand1.render(f5);
		Stand2.render(f5);
		PonyTail.render(f5);
		LeftHeadspike.render(f5);
		RightHeadspike.render(f5);
		HairClip.render(f5);
		Beard1Left.render(f5);
		Beard1Right.render(f5);
		Beard2Left.render(f5);
		Beard2Right.render(f5);
		Beard3.render(f5);
		Beard4Left.render(f5);
		Beard4Right.render(f5);
		Beard5Left.render(f5);
		Beard5Right.render(f5);
		Beard6Left.render(f5);
		Beard6Right.render(f5);
		Beard7Left.render(f5);
		Beard7Right.render(f5);
		Hair.render(f5);
		FaceHairRight.render(f5);
		FaceHairLeft.render(f5);
		BackHair1.render(f5);
		BackHairTail.render(f5);
		LeftShoulder.render(f5);
		RightShoulder.render(f5);
		RightDress.render(f5);
		LeftDress.render(f5);
		Head.render(f5);
		Body.render(f5);
		RightArm.render(f5);
		LeftArm.render(f5);
		RightLeg.render(f5);
		LeftLeg.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z){
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity par6Entity){
		super.setRotationAngles(f, f1, f2, f3, f4, f5, par6Entity);
	}

}
